apiVersion: v2
name: xatu-cannon
description: Ethereum p2p monitoring tool that runs along side a Ethereum consensus client and collects data via the consensus client's Beacon API.
home: https://github.com/ethpandaops/xatu
type: application
version: 0.2.2
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
  - name: savid
    email: andrew.davis@ethereum.org
