apiVersion: v2
name: erpc
description: eRPC is a fault-tolerant EVM RPC proxy and re-org aware permanent caching solution. It is built with read-heavy use-cases in mind such as data indexing and high-load frontend usage.
home: https://github.com/erpc/erpc
type: application
version: 0.0.2
maintainers:
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
  - name: pk910
    email: pk910@pk910.de
