repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        args: []
        description: >
          Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file,
          and inserts the result into a corresponding 'README.md' file.
        entry: jnorwood/helm-docs:v1.5.0
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: docker_image
        require_serial: true
