[default]
extend-ignore-re = [
    # Ignore Ethereum Node Records (ENR)
    "enr:-.*",
    # Ignore blutgang config typo
    "supress_rpc_check",
    # Ignore IPFS CIDs (Content Identifiers)
    "Qm[a-zA-Z0-9]{44}",
]
