apiVersion: v2
name: benchmarkoor-api
description: Benchmarkoor API - Benchmarking tool for Ethereum execution clients.
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: skylenet
    email: rafael@skyle.net
keywords:
  - benchmarkoor
  - ethereum
  - benchmarking
