apiVersion: v2
name: eth-faucet
description: Ether faucet server built with Go and Svelte.
home: https://github.com/chainflag/eth-faucet
type: application
version: 0.1.0
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
