apiVersion: v2
name: xatu-server
description: Ethereum p2p monitoring tool that collects events from and controls various Xatu clients.
home: https://github.com/ethpandaops/xatu
type: application
version: 0.0.12
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
  - name: savid
    email: andrew.davis@ethereum.org
