apiVersion: v2
name: xatu-consumoor
description: Ethereum data consumer tool that processes and forwards blockchain data from various sources.
home: https://github.com/ethpandaops/xatu
type: application
version: 0.0.1
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
  - name: savid
    email: andrew.davis@ethereum.org
