apiVersion: v2
name: erigon
description: Erigon, formerly known as Turbo‐Geth, is a fork of Go Ethereum (geth) oriented toward speed and disk‐space efficiency. Erigon is a completely re-architected implementation of Ethereum, currently written in Go but with implementations in other languages planned. Erigon's goal is to provide a faster, more modular, and more optimized implementation of Ethereum.
home: https://twitter.com/ErigonEth
icon: https://pbs.twimg.com/profile_images/1420080204148576274/-4OFIs2x_400x400.jpg
sources:
  - https://github.com/ledgerwatch/erigon
type: application
version: 1.0.11
maintainers:
  - name: skylenet
    email: rafael@skyle.net
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
