apiVersion: v2
name: blockscout
description: >
  BlockScout provides a comprehensive, easy-to-use interface for users to view, confirm,
  and inspect transactions on EVM (Ethereum Virtual Machine) blockchains
home: https://docs.blockscout.com/
icon: https://github.com/blockscout/blockscout/raw/master/apps/block_scout_web/assets/static/apple-touch-icon.png
sources:
  - https://github.com/blockscout/blockscout/
type: application
version: 0.2.1
maintainers:
  - name: skylenet
    email: rafael@skyle.net
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: smart-contract-verifier-http
    version: "0.1.2"
    repository: "https://ethpandaops.github.io/ethereum-helm-charts"
    condition: smart-contract-verifier-http.enabled
