apiVersion: v2
name: blockscout
description: >
  BlockScout provides a comprehensive, easy-to-use interface for users to view, confirm,
  and inspect transactions on EVM (Ethereum Virtual Machine) blockchains
home: https://docs.blockscout.com/
icon: https://github.com/blockscout/blockscout/raw/master/apps/block_scout_web/assets/static/apple-touch-icon.png
sources:
  - https://github.com/blockscout/blockscout/
type: application
version: 0.1.0
maintainers:
  - name: skylenet
    email: rafael@skyle.net
dependencies:
- name: postgresql
  version: "11.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
