apiVersion: v2
name: ethereumjs
description: >
  The EthereumJS Client is an Ethereum Execution Client (similar to go-ethereum or Nethermind) written in TypeScript/JavaScript, the non-Smart-Contract language Ethereum dApp developers are most familiar with. It is targeted to be a client for research and development and not meant to be used in production on mainnet for the foreseeable future (out of resource and security considerations).
home: https://ethereumjs.readthedocs.io/en/latest/
icon: https://user-images.githubusercontent.com/47108/78779352-d0839500-796a-11ea-9468-fd2a0b3fe1ef.png
sources:
  - https://github.com/ethereumjs/ethereumjs-monorepo
type: application
version: 0.0.9
maintainers:
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
