apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benchmarkoor-api.fullname" . }}
  labels:
    {{- include "benchmarkoor-api.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
