{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benchmarkoor-api.fullname" . }}
  labels:
    {{- include "benchmarkoor-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
