{{- if and .Values.rbac.create .Values.rbac.clusterRules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "xatu-sentry-logs.fullname" . }}
  labels:
    {{- include "xatu-sentry-logs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "xatu-sentry-logs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "xatu-sentry-logs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
