{{- if and .Values.rbac.create .Values.rbac.clusterRules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xatu-sentry-logs.fullname" . }}
  labels:
    {{- include "xatu-sentry-logs.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.clusterRules | nindent 0 }}
{{- end }}
