{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "xatu-sentry-logs.fullname" . }}
  labels:
    {{- include "xatu-sentry-logs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "xatu-sentry-logs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "xatu-sentry-logs.serviceAccountName" . }}
{{- end }}
