apiVersion: v1
kind: Service
metadata:
  name: {{ include "xatu-sentry-logs.fullname" . }}
  labels:
    {{- include "xatu-sentry-logs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4 }}
  {{- end }}
  selector:
    {{- include "xatu-sentry-logs.selectorLabels" . | nindent 4 }}
