apiVersion: v2
name: lodestar
description: Lodestar is a open-source TypeScript implementation of the Ethereum consensus engine.
home: https://lodestar.chainsafe.io/
icon: https://raw.githubusercontent.com/ChainSafe/lodestar/master/assets/lodestar_icon_300.png
sources:
  - https://github.com/ChainSafe/lodestar
type: application
version: 1.2.1
maintainers:
  - name: skylenet
    email: rafael@skyle.net
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
