apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xatu-consumoor.fullname" . }}
  labels:
    {{- include "xatu-consumoor.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ tpl (toYaml .Values.config | nindent 4) $ }}
