apiVersion: v1
kind: Service
metadata:
  name: {{ include "xatu-consumoor.fullname" . }}
  labels:
    {{- include "xatu-consumoor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "xatu-consumoor.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if (include "xatu-consumoor.pprofPort" .) }}
    - port: {{ include "xatu-consumoor.pprofPort" . }}
      targetPort: pprof
      protocol: TCP
      name: pprof
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "xatu-consumoor.selectorLabels" . | nindent 4 }}
