apiVersion: v2
name: fauceth
description: >
  Faucet for EVM chains
home: https://github.com/komputing/fauceth
icon: https://avatars.githubusercontent.com/u/48826811?s=200&v=4
sources:
  - https://github.com/komputing/fauceth
type: application
version: 0.2.4
maintainers:
  - name: skylenet
    email: rafael@skyle.net
