apiVersion: v2
name: ethereum-address-metrics-exporter
description: A prometheus exporter for Ethereum externally owned account and contract addresses
home: https://github.com/savid/ethereum-address-metrics-exporter
type: application
version: 0.0.2
maintainers:
  - name: savid
    email: ansrew.davis@ethereum.org
