apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ethrex.fullname" . }}-env
  labels:
    {{- include "ethrex.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ethrex.fullname" . }}-jwt
type: Opaque
data:
  jwt.hex: {{ .Values.jwt | b64enc }}