apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethrex.fullname" . }}-headless
  labels:
    {{- include "ethrex.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "ethrex.p2pPort" . }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ include "ethrex.p2pPort" . }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.httpPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: {{ .Values.authPort }}
      targetPort: auth-rpc
      protocol: TCP
      name: auth-rpc
    {{- if ne .Values.httpPort .Values.wsPort }}  
    - port: {{ .Values.wsPort }}
      targetPort: ws-rpc
      protocol: TCP
      name: ws-rpc
    {{- end }}
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "ethrex.selectorLabels" . | nindent 4 }}
