{{- if .Values.p2pNodePort.enabled -}}

{{- range $i, $e := until (int $.Values.replicas) }}

{{- $port := add $.Values.p2pNodePort.startAt $i -}}
{{- if hasKey $.Values.p2pNodePort.portsOverwrite ($i | toString) -}}
  {{ $port = index $.Values.p2pNodePort.portsOverwrite ($i | toString) }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nimbus-eth2.fullname" $ }}-p2p-{{ $i }}
  labels:
    {{- include "nimbus-eth2.labels" $ | nindent 4 }}
    pod: {{ include "nimbus-eth2.fullname" $ }}-{{ $i }}
    type: p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ include "nimbus-eth2.p2pPort" $ }}
      protocol: TCP
      targetPort: p2p-tcp
      nodePort: {{ $port }}
    - name: p2p-udp
      port: {{ include "nimbus-eth2.p2pPort" $ }}
      protocol: UDP
      targetPort: p2p-udp
      nodePort: {{ $port }}
  selector:
    {{- include "nimbus-eth2.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ include "nimbus-eth2.fullname" $ }}-{{ $i }}

{{- end }}

{{- end }}
