{{- if .Values.p2pNodePort.enabled -}}

{{- $port := $.Values.p2pNodePort.port -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse.fullname" $ }}-p2p-{{ $i }}
  labels:
    {{- include "lighthouse.labels" $ | nindent 4 }}
    pod: {{ include "lighthouse.fullname" $ }}-{{ $i }}
    type: p2p
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: p2p-tcp
      port: {{ include "lighthouse.p2pPort" $ }}
      protocol: TCP
      targetPort: p2p-tcp
      nodePort: {{ $port }}
    - name: p2p-udp
      port: {{ include "lighthouse.p2pPort" $ }}
      protocol: UDP
      targetPort: p2p-udp
      nodePort: {{ $port }}
  selector:
    {{- include "lighthouse.selectorLabels" $ | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "lighthouse.fullname" $ }}-0"
{{- end }}
