apiVersion: v2
name: dugtrio
description: >
  Fault tolerant load balancer for beacon chain RPC apis
home: https://github.com/ethpandaops/dugtrio
sources:
  - https://github.com/ethpandaops/dugtrio
type: application
version: 0.0.6
appVersion: "1.0.0"
maintainers:
  - name: pk910
    email: philipp@pk910.de
