apiVersion: v2
name: forky
description: A beacon chain fork choice viewer
home: https://github.com/ethpandaops/forky
type: application
version: 0.1.2
maintainers:
  - name: samcm
    email: sam.calder-mason@ethereum.org
  - name: savid
    email: andrew.davis@ethereum.org
