apiVersion: v1
kind: Service
metadata:
  name: {{ include "dugtrio.fullname" . }}
  labels:
    {{- include "dugtrio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "dugtrio.httpPort" . }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.extraPorts }}
    {{ toYaml .Values.extraPorts | nindent 4}}
  {{- end }}
  selector:
    {{- include "dugtrio.selectorLabels" . | nindent 4 }}
