apiVersion: v2
name: dshackle
description: >
  Emerald Dshackle is a Fault Tolerant Load Balancer for Blockchain API.
  Support for standard Bitcoin and Ethereum JSON RPC API over HTTP and WebSocket.
home: https://github.com/emeraldpay/dshackle
icon: https://avatars.githubusercontent.com/u/49622339?s=200&v=4
sources:
  - https://github.com/emeraldpay/dshackle
type: application
version: 0.1.1
maintainers:
  - name: skylenet
    email: rafael@skyle.net
dependencies:
- name: redis
  version: "16.8.9"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
