apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benchmarkoor-ui.fullname" . }}
  labels:
    {{- include "benchmarkoor-ui.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Values.config | nindent 4 }}
