apiVersion: v2
name: light-beaconchain-explorer
description: A Beaconchain explorer is a tool that allows users to view and interact with the data on the Ethereum Beacon Chain. It is similar to a blockchain explorer, which allows users to view data on a blockchain such as the current state of transactions and blocks - but focussed on exploring the beaconchain.
home: https://github.com/pk910/light-beaconchain-explorer
type: application
version: 0.0.1
maintainers:
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
