{{- if .Values.p2pNodePort.enabled -}}
{{- $fullName := include "helm-ipfs-cluster.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName}}-p2p-nodeport
  labels:
    {{- include "helm-ipfs-cluster.selectorLabels" . | nindent 4 }}
    nodeType: ipfs
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 4001
    name: swarm
    targetPort: swarm
    protocol: TCP
    nodePort: {{ .Values.p2pNodePort.nodePort }}
  - port: 4001
    name: swarm-udp
    targetPort: swarm-udp
    protocol: UDP
    nodePort: {{ .Values.p2pNodePort.nodePort }}
  selector:
    {{- include "helm-ipfs-cluster.selectorLabels" . | nindent 4 }}
    nodeType: ipfs
{{- end }}
