apiVersion: v2
name: reth
description: >
  Reth (short for Rust Ethereum, pronunciation) is a new Ethereum full node implementation that is focused on being user-friendly, highly modular, as well as being fast and efficient. Reth is an Execution Layer (EL) and is compatible with all Ethereum Consensus Layer (CL) implementations that support the Engine API. It is originally built and driven forward by Paradigm, and is licensed under the Apache and MIT licenses.
home: https://www.paradigm.xyz/2022/12/reth
icon: https://github.com/paradigmxyz/reth/raw/main/assets/reth.jpg
sources:
  - https://github.com/paradigmxyz/reth/
type: application
version: 0.2.0
maintainers:
  - name: barnabasbusa
    email: busa.barnabas@gmail.com
